### ISSUE TITLE
Missing Copyright-claim

### ISSUE THREAD

**Issue by Andre601** [AndrewAubury/DiscordSupport#2]
This Repository uses the code of [Scarsz lol's SupportBot](https://github.com/Scarsz/DiscordSupportBot) without giving proper copyright notice.

DiscordSupportBot is under the GPL-3.0 license, which has following conditions:
* License and copyright notice
* State changes
* Disclose source
* Same license

None of those requirements are met, which is a violation of this license.

The last issue about this problem ( #1 ) was closed by the repo-owner and the description deleted by him.

Closing this issue without any changes will have a report to GitHub about breaking copyright as a result.

**Comment by AndrewAubury** [comment]
There done. Geez.
